# Generated by Django 5.0.6 on 2024-07-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfoliocdategory_team_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='size',
        ),
    ]
