# Generated by Django 5.0.6 on 2024-07-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_portfolio_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioCdategory',
            new_name='PortfolioCategory',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='author',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
