# Generated by Django 5.0.6 on 2024-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_portfoliocdategory_portfoliocategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='size',
            field=models.CharField(default='col-lg-5', max_length=20),
        ),
    ]
