# Generated by Django 5.0.6 on 2024-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='direction',
            new_name='director',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default='https://github.com/asilbek-ismoilov?tab=repositories'),
        ),
    ]
